from tkinter import *
import sqlite3
con = sqlite3.connect('users.db')
c = con.cursor()
c.execute("CREATE TABLE IF NOT EXISTS user (regno INTEGER PRIMARY KEY, name TEXT, address TEXT, gender TEXT, curstate TEXT, mobile INTEGER, email TEXT, password TEXT)")
con.commit()
root = Tk()
root.geometry('500x690')
root.title("Create Account")
root.config(background="#1b9b6c")

#def validmob():
#def validpass()
def add():
    name = e1.get()
    regid = e2.get()
    add = e3.get()
    gender = e4.get()
    curstat = e5.get()
    mob = e6.get()
    email = e7.get()
    passw = e8.get()
    c.execute("INSERT INTO user(regno,name,address,gender,curstate,mobile,email,password) VALUES (?,?,?,?,?,?)",(regid,name,add,gender,curstat,mob,email,passw ))
    con.commit()
    con.close()

label_0 = Label(root,bg="black",fg="aqua", text="Register Here",width=20,font=("bold", 20))
label_0.place(x=90,y=53)
label_1 = Label(root,bg="black",fg="white", text="Name",width=10)
label_1.place(x=70,y=130)
entry_1 = Entry(root, bd=5, bg="#44cfe2", fg="red")
entry_1.place(x=240,y=130)
label_2 = Label(root,bg="black",fg="white", text="Reg no.",width=10)
label_2.place(x=70,y=180)
entry_2 = Entry(root, bd=5, bg="#44cfe2", fg="red")
entry_2.place(x=240,y=180)
label_3 = Label(root,bg="black",fg="white", text="Address",width=10)
label_3.place(x=70,y=230)
entry_3 = Entry(root, bd=5, bg="#44cfe2", fg="red")
entry_3.place(x=240,y=230)
label_4 = Label(root,bg="black",fg="white", text="Gender",width=10)
label_4.place(x=70,y=280)
#var = StringVar()
R1 = Radiobutton(root,bg="#1b9b6c",fg="white", text="Male", variable='var', value='M')
R1.place(x=235,y=280)
R2 = Radiobutton(root,bg="#1b9b6c",fg="white", text="Female", variable='var', value='F')
R2.place(x=290,y=280)


label_5 = Label(root,bg="black",fg="white", text="Current Status", width=13)
label_5.place(x=70,y=330)
entry_5 = Entry(root, bd=5, bg="#44cfe2", fg="red")
list1 = ['Student','Teacher','Staff','Other']
c=StringVar()
droplist=OptionMenu(root,c, *list1)
droplist.config(width=15, bd=5, bg="#44cfe2", fg="red")
c.set('select your status')
droplist.place(x=240,y=330)
label_6 = Label(root,bg="black",fg="white", text="Mobile No",width=10)
label_6.place(x=70,y=380)
entry_6 = Entry(root, bd=5, bg="#44cfe2", fg="red")
entry_6.place(x=240,y=380)
label_7 = Label(root,bg="black",fg="white", text="Email",width=10)
label_7.place(x=70,y=430)
entry_7 = Entry(root, bd=5, bg="#44cfe2", fg="red")
entry_7.place(x=240,y=430)
label_7 = Label(root,bg="black",fg="white", text="Password",width=10)
label_7.place(x=70,y=480)
entry_7 = Entry(root, bd=5, bg="#44cfe2", fg="red",show="*")
entry_7.place(x=240,y=480)
label_7 = Label(root,bg="black",fg="white", text="Confirm Password",width=15,font=("bold", 10))
label_7.place(x=70,y=530)
entry_7 = Entry(root, bd=5, bg="#44cfe2", fg="red", show="*")
entry_7.place(x=240,y=530)
Button(root, text='REGISTER',width=50,bg='#2D39BF',fg='white').place(x=60,y=580)
Button(root, text='LOGIN',width=50,bg='#2D39BF',fg='white').place(x=60,y=620)
root.mainloop()
